### ISSUE TITLE
Add support for choosing strawberry version

### ISSUE THREAD

**Issue by patrick91** [la4de/strawberry-playground#1]
It would be nice to allow people to chose the version of strawberry when running snippets :D

**Comment by la4de** [comment]
That's great idea. I was thinking about adding that too. We need to first resolve python-multipart installation issue in pyodide before we can make the version configurable. See https://github.com/andrew-d/python-multipart/issues/37

I have built strawberry package manually without that dependency as a workaround to that installation problem.

**Comment by la4de** [comment]
This may help here too. Waiting for next pyodide release :)

https://github.com/pyodide/pyodide/pull/1976

**Comment by la4de** [comment]
Pyodide 0.19 has been released. Need to check if we can now install `strawberry-graphql` even if `python-multipart` dependency installation fails.

**Comment by la4de** [comment]
done!
